name: Node CI - Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            server
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: NPM Clean Install
        run: npm ci
        working-directory: ./server
      - name: NPM Test
        run: npm test
        working-directory: ./server
